name: Build LaTeX document

on:
  push:
    branches: [master, main]
    # paths:
    #   - ".gitea/workflows/latex.yaml"

jobs:
  build-latex:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build LaTeX document
        run: docker run --rm --volumes-from ${{ env.JOB_CONTAINER_NAME }} --workdir ${{ github.workspace }} gitea.vps.chriphost.de/christoph/texlive:latest latexmk -shell-escape -pdf <MAIN-FILE>.tex
      - name: Rename artifact
        run: mv <MAIN-FILE>.pdf <ARTIFACT-NAME>.pdf
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: <ARTIFACT-NAME>.pdf
          path: <ARTIFACT-NAME>.pdf
